core/urls.py
from django.urls import path
from .views import BookCreateView, BookIssueCreateView, BookIssueListView, general_login, logout, member_register, BookListView, ProfileUpdateView, update_return_date


app_name='core'
urlpatterns = [
  path('login',general_login, name='login'),
  path('logout', logout, name='logout'),
  path('register', member_register, name='register'),
  path('', BookListView.as_view(), name='index'),
  path('profile/<str:username>', ProfileUpdateView.as_view(), name='profile-update'),
  path('add-book', BookCreateView.as_view(), name='add-book'),
  path('issue-book', BookIssueCreateView.as_view(), name='issue-book'),
  path('issue-list', BookIssueListView.as_view(),name='issue-list'),
  path('api/update-return-date/<int:pk>', update_return_date, name = 'return-date-api')
]

library_management/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponseRedirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('core/', include('core.urls')),
    path('', lambda request: HttpResponseRedirect('/core/')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.utils import timezone 
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class User(AbstractUser):
  ADMIN=0
  LIBRARIAN=1
  MEMBER=2
  USER_LEVEL_CHOICES=(
    (ADMIN, "Admin"),
    (LIBRARIAN, "Librarian"),
    (MEMBER,"Member")
  )
  email = models.EmailField(unique=True)
  role = models.IntegerField(choices=USER_LEVEL_CHOICES, blank=True, default=MEMBER)

  USERNAME_FIELD='email'
  REQUIRED_FIELDS=['username']
  
  def __str__(self):
    return self.username
  def save(self, *args, **kwargs):
    if self.is_staff and self.role !=0:
      self.role = 0
    super().save(*args, **kwargs)

class Profile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  full_name =  models.CharField(max_length=255, null=True, blank=True)
  image = models.ImageField(blank=True, null=True, upload_to='uploads/profile')
  address = models.CharField(null=True, blank=True, max_length=255)
  
  def __str__(self):
    if self.full_name:
      return self.full_name
    return self.user.username 
  
  

class Book(models.Model):
  title = models.CharField(max_length=255, blank=False)
  author = models.CharField(max_length=200, blank=True)
  created_at = models.DateTimeField(auto_now_add=True)
  total_copies=models.IntegerField(default=1, blank=True)
  available_copies = models.IntegerField(default=0, blank=True)

  def __str__(self):
    return self.title
  def save(self, *args, **kwargs):
    if self._state.adding and (self.available_copies==0):
      self.available_copies = self.total_copies
    super().save(*args, **kwargs)
      
  
class BookIssue(models.Model):
  member = models.ForeignKey('User', on_delete=models.SET_NULL, null=True, related_name='book_issue_member',  limit_choices_to={'role': '2'})
  book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
  issued_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='book_issue_librarian')
  issue_date = models.DateField(blank=False, auto_now_add=True)
  due_date = models.DateField(blank=False, auto_now_add=False)
  return_date = models.DateField(null=True)
  is_returned = models.BooleanField(default=False)

  def __str__(self):
    return f'{self.member.username} - {self.book.title}'
  
  def save(self, *args, **kwargs):
    if self.is_returned == True and self.return_date is None:
      self.return_date = timezone.now().date()
    super().save(*args, **kwargs)



  

core/forms.py
from django import forms
from .models import Book, BookIssue, Profile, User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
  email = forms.EmailField()
  first_name = forms.CharField(max_length = 20)
  last_name = forms.CharField(max_length = 20)
  
  class Meta:
    model = User
    fields = ['username', 'email', 'password1', 'password2']
  
  def save(self, commit=True):
    user = super().save(commit=False)
    user.email=self.cleaned_data.get('email')
    user.first_name=self.cleaned_data.get('first_name')
    user.last_name=self.cleaned_data.get('last_name')
    user.role=User.MEMBER
    if commit:
      user.save()
    return user
  
class ProfileForm(forms.ModelForm):
  class Meta:
    model = Profile
    fields = ['image', 'full_name', 'address']
    widgets = {
      'image': forms.ClearableFileInput(
        attrs={
          'class': 'form-control'          
        } 
      ),
      'full_name':forms.TextInput(attrs={
        'class':'form-control'
      }),
      'address': forms.Textarea(attrs={
        'class':'form-control',
        'placeholder':'Enter your address'
      })
    }
  def save(self, user=None, *args, **kwargs):
    profile = super().save(commit=False)
    profile.user = user or profile.user
    profile.save()
    return profile

class BookForm(forms.ModelForm):
  class Meta:
    model = Book
    fields = ['title', 'author', 'total_copies', 'available_copies']
    widgets = {
      'title': forms.TextInput(attrs={
        'class':'form-control',        
      }),
      'author': forms.TextInput(attrs={
        'class': 'form-control'
      }),
      'total_copies':forms.NumberInput(attrs={
        'class':'form-control'
      }),
      'available_copies':forms.NumberInput(attrs={
        'class':'form-control'
      })
    }

class BookIssueForm(forms.ModelForm):
  class Meta:
    model = BookIssue
    fields = ['member','book', 'due_date']
    widgets = {
      'member':forms.Select(attrs={
        'class':'form-control'
      }),
      'book':forms.Select(attrs={
        'class':'form-control'
      }),

      'due_date': forms.DateInput(attrs={
      'class': 'form-control',
      'type': 'date'
    }),
    }
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.fields['book'].empty_label = 'Choose book'
    self.fields['member'].empty_label = 'Choose a member'

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from .models import Book, Profile, User, BookIssue
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView
from .forms import BookForm, BookIssueForm, ProfileForm, UserRegisterForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.utils import timezone

# Create your views here.

def member_register(request):
  if request.method=='POST':
    form = UserRegisterForm(request.POST)

    if form.is_valid():
      form.save()
      username = form.cleaned_data.get('username')
      messages.success(request,f'Your account has been created with the username {username}')
      return redirect('core:login')
  else:
    form =UserRegisterForm()
  
  context = {
    'form':form,
  }
  return render(request, 'register.html', context)

def general_login(request):
  if request.user.is_authenticated and request.user.role !=0:
    return redirect('core:index')
  
  
  if request.method=='POST':
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None and user.role !=0:
      form=login(request,user)
      messages.success(request,f'Welcome, {request.user.username}')
      return redirect('core:index')
    else:
      messages.info(request, f'Account name does not exist, Please signup')
  
  form = AuthenticationForm()
  context={
    'form':form
  }
  return render(request, 'login.html', context)

class AdminNotAllowed:
  def dispatch(self, request, *args, **kwargs):
    if(request.user.role==0):
      messages.error(request,f'Admin cant login here')
      return redirect('core:login')
    return super().dispatch(request, *args, **kwargs)
  
class BookListView(LoginRequiredMixin,AdminNotAllowed, ListView):
  model = Book
  paginate_by = 10
  template_name='index.html'
  ordering = ['created_at']
  login_url='core:login'



class ProfileUpdateView(LoginRequiredMixin, AdminNotAllowed, UpdateView):
  model = Profile
  form_class = ProfileForm
  template_name = 'profile.html'
  login_url='core:login'

  def get_object(self, queryset=None):
    return Profile.objects.get(user__username=self.kwargs['username'])
  
  def get_success_url(self):
    return reverse_lazy('core:profile-update', kwargs={'username': self.request.user.username})

#if we use the generic view only
# class ProfileUpdateView(LoginRequiredMixin, AdminNotAllowed, UpdateView):
#   model = Profile
#   fields = ['image', 'full_name', 'address']
#   template_name = 'profile.html'
#   def get_object(self, queryset=None):
#     return get_object_or_404(Profile, user__username=self.kwargs['username'])

#   def get_success_url(self):
#     return reverse_lazy('profile', kwargs={'username': self.request.user.username})

class BookCreateView(LoginRequiredMixin, AdminNotAllowed, CreateView):
  model = Book
  form_class = BookForm
  template_name = 'book.html'
  login_url='core:login'
  
  def get_success_url(self):
    messages.success(self.request, f'Successfully added the new book')
    return reverse_lazy('core:index')

class BookIssueCreateView(LoginRequiredMixin, AdminNotAllowed, CreateView):
  model = BookIssue
  form_class = BookIssueForm
  template_name = 'book-issue.html'
  login_url = 'core:login'

  def form_valid(self, form):
    form.instance.issued_by = self.request.user
    messages.success(self.request, f'Successfully issued to {form.instance.member.username}')
    return super().form_valid(form)
  

  def get_success_url(self):
    
    return reverse_lazy('core:index')
  
class BookIssueListView(LoginRequiredMixin, AdminNotAllowed, ListView):
  model = BookIssue
  paginate_by = 10
  template_name='issue-list.html'
  ordering = ['return_date']
  login_url='core:login'
  def get_queryset(self):
    if self.request.user.role == 2:
      return BookIssue.objects.filter(member=self.request.user).order_by('return_date')  
    return BookIssue.objects.all().order_by('return_date')

def update_return_date(request, pk):
  try:
    issue = BookIssue.objects.get(id=pk)

    issue.return_date = timezone.now().date()
    issue.is_returned = True
    book = issue.book
    book.available_copies = min(book.total_copies, book.available_copies+1)
    book.save()
    issue.save()

    return JsonResponse({
      'success': True,
      'message': f'Return date updated for {issue.book.title}',
      'return_date': issue.return_date,
    })

  except BookIssue.DoesNotExist:
    return JsonResponse({'success': False, 'message': 'Book issue not found'}, status=404)

core/templates/book-issue.html
{% extends 'book.html' %}

core/templates/book.html
{% extends 'base/base.html' %} {% block title %} Add Book {% endblock title %}
{% block content %} {% block form_template %}
<div class="container">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <input type="submit" value="Save" />
  </form>
</div>

{% endblock form_template %} {% endblock content %}

core/templates/index.html
{% extends 'base/base.html' %} {% block title %} Homepage {% endblock title %}
{% block content %}
<div class="container">
  <table class="table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Author</th>
      <th scope="col">Available copies</th>        
    </tr>
  </thead>
  <tbody>
    {% for book in page_obj %}
    <tr>
      <td>{{book.title}}</td>
      <td>{{book.author}}</td>
      <td>{{book.available_copies}}</td>
    </tr>
    {% endfor %}
    
  </tbody>
  

</table>

<ul class="pagination">
  {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page=1" aria-label="First">
        <span aria-hidden="true">&laquo;&laquo;</span>
      </a>
    </li>
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
  {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo;&laquo;</span>
    </li>
    <li class="page-item disabled">
      <span class="page-link">&laquo;</span>
    </li>
  {% endif %}

  {# Page number loop #}
  {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
      <li class="page-item active">
        <span class="page-link">{{ num }}</span>
      </li>
    {% elif num >= page_obj.number|add:-2 and num <= page_obj.number|add:2 %}
      <li class="page-item">
        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
      </li>
    {% endif %}
  {% endfor %}

  {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
        <span aria-hidden="true">&raquo;&raquo;</span>
      </a>
    </li>
  {% else %}
    <li class="page-item disabled">
      <span class="page-link">&raquo;</span>
    </li>
    <li class="page-item disabled">
      <span class="page-link">&raquo;&raquo;</span>
    </li>
  {% endif %}
</ul>



{% endblock content %}

core/templates/issue-list.html
{% extends 'base/base.html' %}

{% block title %}
  Issue list
{% endblock title %}


{% block content %}
  <div class="container">
    
    {% if user.is_authenticated and user.role == 1 %}
      <a href="{% url 'core:issue-book' %}" class="btn btn-primary m-2 float-end">New issue</a>
    {% endif %}
      
  
  <table class="table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      
      {% if user.role is 1 %}
        <th scope="col">Issued To</th>
      {% endif %}
        
      
      <th scope="col">Due date</th>
      <th scope="col">Return date</th>
      {% if user.role is 1 %}
        <th scope="col">Manage</th>
      {% endif %}
        
    </tr>
  </thead>
  <tbody>
    {% for book_issue in page_obj %}
    <tr>
      <td>{{book_issue.book}}</td>
      {% if user.role is 1 %}
      <td>{{book_issue.member}}</td>
      {% endif %}
      <td>{{book_issue.due_date}}</td>
      <td>
        
        {% if book_issue.return_date is None %}
          Not returned
        {% else %}
        {{book_issue.return_date}}
        {% endif %}
        
          
      </td>
      {% if user.role == 1 %}
        <td data-id="{{ book_issue.id }}">
          {% if not book_issue.return_date %}
            <button class="btn btn-secondary">Update</button>
          {% else %}
            <button class="btn btn-secondary disabled">Update</button>
          {% endif %}
        </td>
      {% endif %}


    </tr>
    {% endfor %}
    
  </tbody>
  

</table>

<ul class="pagination">
  {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page=1" aria-label="First">
        <span aria-hidden="true">&laquo;&laquo;</span>
      </a>
    </li>
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
  {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo;&laquo;</span>
    </li>
    <li class="page-item disabled">
      <span class="page-link">&laquo;</span>
    </li>
  {% endif %}

  {# Page number loop #}
  {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
      <li class="page-item active">
        <span class="page-link">{{ num }}</span>
      </li>
    {% elif num >= page_obj.number|add:-2 and num <= page_obj.number|add:2 %}
      <li class="page-item">
        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
      </li>
    {% endif %}
  {% endfor %}

  {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
        <span aria-hidden="true">&raquo;&raquo;</span>
      </a>
    </li>
  {% else %}
    <li class="page-item disabled">
      <span class="page-link">&raquo;</span>
    </li>
    <li class="page-item disabled">
      <span class="page-link">&raquo;&raquo;</span>
    </li>
  {% endif %}
</ul>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function () {
    $('.btn-secondary').on('click', function () {
   const row = $(this).closest('td');
   const bookIssueId = row.data('id');

   const confirmReturn = confirm('Are you sure you want to mark this book as returned and set today as the return date?');

   if (!confirmReturn) return;

   $.ajax({
     url: `api/update-return-date/${bookIssueId}`,
     type: 'GET',
     dataType: 'json',
     success: function (response) {
       if (response.success) {
         alert(response.message);
         // Update the DOM with return date
         window.location.reload();
       } else {
         alert('Update failed: ' + response.message);
       }
     },
     error: function (xhr) {
       alert(xhr.message);
     }
   });
} );

  });
</script>

{% endblock content %}
  

core/templates/login.html
{% extends 'base/base.html' %} {% load crispy_forms_tags %} 
{% block title %}
Login {% endblock title %} {% block content %}
<h1 class="text-center">Login</h1>
  <div class="container">
    <form
      method="POST"
      style="
        border: 1px solid black;
        margin: 4%;
        padding: 5%;
        border-radius: 8px;
      "
    >
      {% csrf_token %}
      <fieldset class="form-group">{{ form|crispy }}</fieldset>
      <center>
        <button
          style="
            background: black;
            padding: 1.5% 4%;
            font-size: 1.5rem;
            color: white;
          "
          type="submit"
        >
          <span class="glyphicon glyphicon-check"></span>   Login
        </button>
      </center>
      <br />
      <sub>
        <a
          href="{% url 'core:register' %}"
          style="text-decoration: none; color: blue"
        >
          Don't have an account?
        </a>
      </sub>
    </form>
  </div>

{% endblock content %}

core/templates/profile.html
{% extends 'base/base.html' %} {% block content %}
<div class="container">
  <form method="post" enctype="multipart/form-data">
    {% if form.instance.image %}
    <img
      src="{{ form.instance.image.url }}"
      alt="Profile Image"
      width="150"
      height="150"
      style="object-fit: cover; border-radius: 10px"
    />
    {% else %}
    <p>No image uploaded.</p>
    {% endif %} {% csrf_token %} {{ form.as_p }}
    <input type="submit" value="Update" />
  </form>
</div>

{% endblock content %}

core/templates/register.html
{% extends 'base/base.html' %}
{% block title %}
  Register
{% endblock title %}
  
{% block content %}
  <h1>
    Register
  </h1>
{% endblock content %}
    