core/urls.py
from django.urls import path
from .views import BookCreateView, BookIssueCreateView, BookIssueListView, general_login, logout, member_register, BookListView, ProfileUpdateView, update_return_date


app_name='core'
urlpatterns = [
  path('login',general_login, name='login'),
  path('logout', logout, name='logout'),
  path('register', member_register, name='register'),
  path('', BookListView.as_view(), name='index'),
  path('profile/<str:username>', ProfileUpdateView.as_view(), name='profile-update'),
  path('add-book', BookCreateView.as_view(), name='add-book'),
  path('issue-book', BookIssueCreateView.as_view(), name='issue-book'),
  path('issue-list', BookIssueListView.as_view(),name='issue-list'),
  path('api/update-return-date/<int:pk>', update_return_date, name = 'return-date-api')
]

library_management/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponseRedirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('core/', include('core.urls')),
    path('', lambda request: HttpResponseRedirect('/core/')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.utils import timezone 
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class User(AbstractUser):
  ADMIN=0
  LIBRARIAN=1
  MEMBER=2
  USER_LEVEL_CHOICES=(
    (ADMIN, "Admin"),
    (LIBRARIAN, "Librarian"),
    (MEMBER,"Member")
  )
  email = models.EmailField(unique=True)
  role = models.IntegerField(choices=USER_LEVEL_CHOICES, blank=True, default=MEMBER)

  USERNAME_FIELD='email'
  REQUIRED_FIELDS=['username']
  
  def __str__(self):
    return self.username
  def save(self, *args, **kwargs):
    if self.is_staff and self.role !=0:
      self.role = 0
    super().save(*args, **kwargs)

class Profile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  full_name =  models.CharField(max_length=255, null=True, blank=True)
  image = models.ImageField(blank=True, null=True, upload_to='uploads/profile')
  address = models.CharField(null=True, blank=True, max_length=255)
  
  def __str__(self):
    if self.full_name:
      return self.full_name
    return self.user.username 
  
  

class Book(models.Model):
  title = models.CharField(max_length=255, blank=False)
  author = models.CharField(max_length=200, blank=True)
  created_at = models.DateTimeField(auto_now_add=True)
  total_copies=models.IntegerField(default=1, blank=True)
  available_copies = models.IntegerField(default=0, blank=True)

  def __str__(self):
    return self.title
  def save(self, *args, **kwargs):
    if self._state.adding and (self.available_copies==0):
      self.available_copies = self.total_copies
    super().save(*args, **kwargs)
      
  
class BookIssue(models.Model):
  member = models.ForeignKey('User', on_delete=models.SET_NULL, null=True, related_name='book_issue_member',  limit_choices_to={'role': '2'})
  book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
  issued_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='book_issue_librarian')
  issue_date = models.DateField(blank=False, auto_now_add=True)
  due_date = models.DateField(blank=False, auto_now_add=False)
  return_date = models.DateField(null=True)
  is_returned = models.BooleanField(default=False)

  def __str__(self):
    return f'{self.member.username} - {self.book.title}'
  
  def save(self, *args, **kwargs):
    if self.is_returned == True and self.return_date is None:
      self.return_date = timezone.now().date()
    super().save(*args, **kwargs)



  

core/forms.py
from django import forms
from .models import Book, BookIssue, Profile, User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
  email = forms.EmailField()
  first_name = forms.CharField(max_length = 20)
  last_name = forms.CharField(max_length = 20)
  
  class Meta:
    model = User
    fields = ['username', 'email', 'password1', 'password2']
  
  def save(self, commit=True):
    user = super().save(commit=False)
    user.email=self.cleaned_data.get('email')
    user.first_name=self.cleaned_data.get('first_name')
    user.last_name=self.cleaned_data.get('last_name')
    user.role=User.MEMBER
    if commit:
      user.save()
    return user
  
class ProfileForm(forms.ModelForm):
  class Meta:
    model = Profile
    fields = ['image', 'full_name', 'address']
    widgets = {
      'image': forms.ClearableFileInput(
        attrs={
          'class': 'form-control'          
        } 
      ),
      'full_name':forms.TextInput(attrs={
        'class':'form-control'
      }),
      'address': forms.Textarea(attrs={
        'class':'form-control',
        'placeholder':'Enter your address'
      })
    }
  def save(self, user=None, *args, **kwargs):
    profile = super().save(commit=False)
    profile.user = user or profile.user
    profile.save()
    return profile

class BookForm(forms.ModelForm):
  class Meta:
    model = Book
    fields = ['title', 'author', 'total_copies', 'available_copies']
    widgets = {
      'title': forms.TextInput(attrs={
        'class':'form-control',        
      }),
      'author': forms.TextInput(attrs={
        'class': 'form-control'
      }),
      'total_copies':forms.NumberInput(attrs={
        'class':'form-control'
      }),
      'available_copies':forms.NumberInput(attrs={
        'class':'form-control'
      })
    }

class BookIssueForm(forms.ModelForm):
  class Meta:
    model = BookIssue
    fields = ['member','book', 'due_date']
    widgets = {
      'member':forms.Select(attrs={
        'class':'form-control'
      }),
      'book':forms.Select(attrs={
        'class':'form-control'
      }),

      'due_date': forms.DateInput(attrs={
      'class': 'form-control',
      'type': 'date'
    }),
    }
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.fields['book'].empty_label = 'Choose book'
    self.fields['member'].empty_label = 'Choose a member'

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from .models import Book, Profile, User, BookIssue
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView
from .forms import BookForm, BookIssueForm, ProfileForm, UserRegisterForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.utils import timezone

# Create your views here.

def member_register(request):
  if request.method=='POST':
    form = UserRegisterForm(request.POST)

    if form.is_valid():
      form.save()
      username = form.cleaned_data.get('username')
      messages.success(request,f'Your account has been created with the username {username}')
      return redirect('core:login')
  else:
    form =UserRegisterForm()
  
  context = {
    'form':form,
  }
  return render(request, 'register.html', context)

def general_login(request):
  if request.user.is_authenticated and request.user.role !=0:
    return redirect('core:index')
  
  
  if request.method=='POST':
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None and user.role !=0:
      form=login(request,user)
      messages.success(request,f'Welcome, {request.user.username}')
      return redirect('core:index')
    else:
      messages.info(request, f'Account name does not exist, Please signup')
  
  form = AuthenticationForm()
  context={
    'form':form
  }
  return render(request, 'login.html', context)

class AdminNotAllowed:
  def dispatch(self, request, *args, **kwargs):
    if(request.user.role==0):
      messages.error(request,f'Admin cant login here')
      return redirect('core:login')
    return super().dispatch(request, *args, **kwargs)
  
class BookListView(LoginRequiredMixin,AdminNotAllowed, ListView):
  model = Book
  paginate_by = 10
  template_name='index.html'
  ordering = ['created_at']
  login_url='core:login'



class ProfileUpdateView(LoginRequiredMixin, AdminNotAllowed, UpdateView):
  model = Profile
  form_class = ProfileForm
  template_name = 'profile.html'
  login_url='core:login'

  def get_object(self, queryset=None):
    return Profile.objects.get(user__username=self.kwargs['username'])
  
  def get_success_url(self):
    return reverse_lazy('core:profile-update', kwargs={'username': self.request.user.username})

#if we use the generic view only
# class ProfileUpdateView(LoginRequiredMixin, AdminNotAllowed, UpdateView):
#   model = Profile
#   fields = ['image', 'full_name', 'address']
#   template_name = 'profile.html'
#   def get_object(self, queryset=None):
#     return get_object_or_404(Profile, user__username=self.kwargs['username'])

#   def get_success_url(self):
#     return reverse_lazy('profile', kwargs={'username': self.request.user.username})

class BookCreateView(LoginRequiredMixin, AdminNotAllowed, CreateView):
  model = Book
  form_class = BookForm
  template_name = 'book.html'
  login_url='core:login'
  
  def get_success_url(self):
    messages.success(self.request, f'Successfully added the new book')
    return reverse_lazy('core:index')

class BookIssueCreateView(LoginRequiredMixin, AdminNotAllowed, CreateView):
  model = BookIssue
  form_class = BookIssueForm
  template_name = 'book-issue.html'
  login_url = 'core:login'

  def form_valid(self, form):
    form.instance.issued_by = self.request.user
    messages.success(self.request, f'Successfully issued to {form.instance.member.username}')
    return super().form_valid(form)
  

  def get_success_url(self):
    
    return reverse_lazy('core:index')
  
class BookIssueListView(LoginRequiredMixin, AdminNotAllowed, ListView):
  model = BookIssue
  paginate_by = 10
  template_name='issue-list.html'
  ordering = ['return_date']
  login_url='core:login'
  def get_queryset(self):
    if self.request.user.role == 2:
      return BookIssue.objects.filter(member=self.request.user).order_by('return_date')  
    return BookIssue.objects.all().order_by('return_date')

def update_return_date(request, pk):
  try:
    issue = BookIssue.objects.get(id=pk)

    issue.return_date = timezone.now().date()
    issue.is_returned = True
    book = issue.book
    book.available_copies = min(book.total_copies, book.available_copies+1)
    book.save()
    issue.save()

    return JsonResponse({
      'success': True,
      'message': f'Return date updated for {issue.book.title}',
      'return_date': issue.return_date,
    })

  except BookIssue.DoesNotExist:
    return JsonResponse({'success': False, 'message': 'Book issue not found'}, status=404)

core/templates/base/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Library management - {% block title %} {% endblock title %}</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
    <link rel="stylesheet" href="" />
    <!-- Toastr CSS -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"
      rel="stylesheet"
    />

    <style>
      .btn {
        padding: 0.45rem 1.5rem 0.35rem;
      }

      .gradient-custom {
        /* fallback for old browsers */
        background: #c471f5;

        /* Chrome 10-25, Safari 5.1-6 */
        background: -webkit-linear-gradient(
          to right,
          rgba(196, 113, 245, 1),
          rgba(250, 113, 205, 1)
        );

        /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        background: linear-gradient(
          to right,
          rgba(196, 113, 245, 1),
          rgba(250, 113, 205, 1)
        );
      }
      load .btn-outline-light {
        --mdb-btn-hover-bg: transparent;
        --mdb-btn-active-bg: transparent;
      }
    </style>
  </head>
  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark gradient-custom">
      <!-- Container wrapper -->
      <div class="container-fluid">
        <!-- Navbar brand -->
        <a class="navbar-brand" href="{% url 'core:index' %}"
          >Library Management</a
        >

        <!-- Toggle button -->
        <button
          class="navbar-toggler"
          type="button"
          data-mdb-collapse-init
          data-mdb-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fas fa-bars text-light"></i>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Left links -->
          <ul class="navbar-nav me-auto d-flex flex-row mt-3 mt-lg-0">
            <li class="nav-item text-center mx-2 mx-lg-1">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'core:index' %}"
              >
                <div>
                  <i class="fas fa-home fa-lg mb-1"></i>
                </div>
                Home
              </a>
            </li>
            {% comment %}
            <li class="nav-item text-center mx-2 mx-lg-1">
              <a class="nav-link" href="#!">
                <div>
                  <i class="far fa-envelope fa-lg mb-1"></i>
                </div>
                Link
              </a>
            </li>
            <li class="nav-item text-center mx-2 mx-lg-1">
              <a class="nav-link disabled" aria-disabled="true" href="#!">
                <div>
                  <i class="far fa-envelope fa-lg mb-1"></i>
                </div>
                Disabled
              </a>
            </li>
            <li class="nav-item dropdown text-center mx-2 mx-lg-1">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-mdb-dropdown-init
                aria-expanded="false"
              >
                <div>
                  <i class="far fa-envelope fa-lg mb-1"></i>
                </div>
                Dropdown
              </a>
              <!-- Dropdown menu -->
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li>
                  <hr class="dropdown-divider" />
                </li>
                <li>
                  <a class="dropdown-item" href="#">Something else here</a>
                </li>
              </ul>
            </li>
            {% endcomment %}
          </ul>
          <!-- Left links -->

          <!-- Right links -->
          <ul class="navbar-nav ms-auto d-flex flex-row mt-3 mt-lg-0">
            <li class="nav-item text-center mx-2 mx-lg-1">
              {% if user.is_authenticated and not user.is_staff%}
              <a class="nav-link" href="{% url 'core:profile-update' user.username%}">{{user.username}}</a>
               {% else %}
              <a class="nav-link" href="{% url 'core:login' %}"> Login </a>

              {% endif %}
            </li>
            {% if user.is_authenticated and user.role == 1 %}
            <li class="nav-item text-center mx-2 mx-lg-1">
              <a class="nav-link" href="{% url 'core:add-book' %}"> Add book </a>
            </li>
            <li class="nav-item text-center mx-2 mx-lg-1">
              <a class="nav-link" href="{% url 'core:issue-list' %}"> Issued books </a>
            </li>
            {% endif %}
            {% if user.is_authenticated and user.role == 2 %}
            <li class="nav-item text-center mx-2 mx-lg-1">
              <a class="nav-link" href="{% url 'core:issue-list' %}"> Issued books </a>
            </li>
            {% endif %}
            {% if user.is_authenticated and not user.is_staff %}
            <li class="nav-item text-center mx-2 mx-lg-1">
              <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button class="nav-link text-black" type="submit">
                  Log Out
                </button>
              </form>
            </li>
            {% endif %}
          </ul>
          <!-- Right links -->
        </div>
        <!-- Collapsible wrapper -->
      </div>
      <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->

    {% block content %} {% endblock content %}
    <!-- jQuery (required) -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Toastr JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script>
      {% if messages %}
        {% for message in messages %}
          toastr.options = {
            "closeButton": true,
            "progressBar": true,
            "timeOut": "5000"
          };
          toastr["{{ message.tags }}"]("{{ message|escapejs }}");
        {% endfor %}
      {% endif %}
    </script>
  </body>
</html>